---
# vars file for packages
# exclude packages list
packages:
  - apt-transport-https
  - aptitude
  - curl
  - deja-dup
  - git
  - htop
  - jq
  - keepass2
  - mlocate
  - vim
  - wget
  - xdotool
  - yakuake