---
- name: Remove go binary directory if present
  become: yes
  file:
    path: /usr/local/go
    state: absent

- name: Download go {{ go_version }}
  get_url:
    url: "https://golang.org/dl/go{{ go_version }}.linux-amd64.tar.gz"
    dest: "/tmp/go{{ go_version }}.linux-amd64.tar.gz"
    mode: 0440

- name: Extract go {{ go_version }} archive into /usr/local
  become: yes
  unarchive:
    src: "/tmp/go{{ go_version }}.linux-amd64.tar.gz"
    dest: /usr/local
    remote_src: yes

- name: Setting username variable
  set_fact:
    username: "{{ ansible_user_id }}"

- name: Add go {{ go_version }} to PATH in ./home/{{ username }}/.zshrc
  become: yes
  lineinfile:
    path: "/home/{{ username }}/.zshrc"
    state: present
    line: export PATH=$PATH:/usr/local/go/bin
