---
- name: Install helm repository key
  become: yes
  apt_key:
    url: "{{ repo_key_url }}"
    state: present

- name: Add helm repository to sources list
  become: yes
  apt_repository:
    repo: "{{ repo_url }}"
    state: present
    filename: helm

- name: Install helm
  become: yes
  apt:
    state: present
    update_cache: yes
    name:
      - helm