---
- name: Install helm repository key
  become: yes
  apt_key:
    url: https://baltocdn.com/helm/signing.asc
    state: present

- name: Clear helm repository sources list
  become: yes
  apt_repository:
    repo: deb https://baltocdn.com/helm/stable/debian/ all main
    state: absent
    filename: helm

- name: Add helm repository to sources list
  become: yes
  apt_repository:
    repo: deb https://baltocdn.com/helm/stable/debian/ all main
    state: present
    filename: helm

- name: Install helm
  become: yes
  apt:
    state: present
    update_cache: yes
    name:
      - helm