---
- name: Install Google Chrome browser repository key
  become: yes
  apt_key:
    url: "{{ repo_signing_key }}"
    state: present
  when: ansible_os_family == 'Debian'

- name: Add Google Chrome browser repository to sources list
  become: yes
  apt_repository:
    repo: "{{ repo_url }}"
    state: present
    filename: google-chrome
  when: ansible_os_family == 'Debian'

- name: Install Google Chrome browser
  become: yes
  apt:
    state: present
    update_cache: yes
    name:
      - google-chrome-stable
  when: ansible_os_family == 'Debian'