---
- name: Setup workstation
  gather_facts: yes
  connection: local
  hosts: localhost
  roles:
    - role: packages
    - role: helper
    - role: vscode
    - role: google-chrome
    - role: google-cloud-cli
    - role: helm
    - role: kubectl
    - role: minikube
      enabled: False
    - role: ohmyzsh
    - role: fonts
    - role: language
    - role: flameshot
    - role: spotify
      enabled: False
    - role: terraform
    - role: slack
    - role: sops
    - role: geerlingguy.docker
      become: yes
