---
- name: Setup workstation
  gather_facts: yes
  connection: local
  hosts: localhost
  roles:
    - packages
    - distrobox
    - fonts
    - language
    - chrome
    - vscode
    # - virtualbox
    # - golang
    - google_cloud_sdk
    - helm
    - kubectl
    - minikube
    - ohmyzsh
    - flameshot
    - helper
    - spotify
    - terraform
    - role: geerlingguy.docker
      become: yes
