---
- name: Setup workstation
  gather_facts: yes
  connection: local
  hosts: localhost
  roles:
    - role: packages
      enabled: True
    - role: distrobox
      enabled: False
    - role: fonts
      enabled: False
    - role: language
      enabled: False
    - role: chrome
      enabled: True
    - role: vscode
      enabled: True
    # - virtualbox
    # - golang
    - role: google_cloud_sdk
      enabled: False
    - role: helm
      enabled: False
      version: v3.14.2
    - role: kubectl
      enabled: False
    - role: minikube
      enabled: False
    - role: ohmyzsh
      enabled: True
    - role: flameshot
      enabled: True
    - role: helper
      enabled: True
    - role: spotify
      enabled: False
    - role: terraform
      enabled: False
    - role: geerlingguy.docker
      become: yes
