---
- name: Setup workstation
  gather_facts: yes
  connection: local
  hosts: localhost
  roles:
    - packages
    - fonts
    # - language
    - chrome
    # - docker
    - vscode
    # - virtualbox
    # - golang
    - google_cloud_sdk
    # - helm
    # - kubectl
    # - minikube
    - ohmyzsh
    - flameshot
    - helper
    # TODO: add tfswitch: https://github.com/warrensbox/terraform-switcher
