---
- name: Install common packages
  become: yes
  package:
    state: present
    name: "{{ packages_common }}"

- name: Install debian packages
  become: yes
  apt:
    state: present
    update_cache: yes
    name: "{{ packages_ubuntu }}"
  when: ansible_os_family == 'Debian'

- name: Install common pip packages
  become: yes
  pip:
    state: present
    name: "{{ packages_pip }}"
