---
- name: Install common packages for Ubuntu
  become: yes
  apt:
    state: present
    update_cache: yes
    name: "{{ common_packages }}"
  when: ansible_os_family == 'Debian'

- name: Install common packages for Fedora
  become: yes
  dnf:
    state: present
    update_cache: yes
    name: "{{ common_packages }}"
  when: ansible_os_family == 'RedHat'

- name: Install debian packages
  become: yes
  apt:
    state: present
    update_cache: yes
    name: "{{ packages_ubuntu }}"
  when: ansible_os_family == 'Debian'