---
# Ubuntu
- name: Downloads and installs vscode deb package
  become: yes
  apt:
    state: present
    deb: "{{ deb_url }}"
  when: ansible_os_family == 'Debian'

# Fedora
- name: Import vscode gpg key
  become: yes
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc
  when: ansible_os_family == 'RedHat'

- name: Add vscode repository
  become: yes
  yum_repository:
    name: vscode
    description: RPM repository of vscode
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgcheck: yes
    enabled: yes
    repo_gpgcheck: yes
    gpgkey:
     - https://packages.microsoft.com/keys/microsoft.asc
  when: ansible_os_family == 'RedHat'

- name: Installing vscode
  become: yes
  dnf:
    name: code
    state: latest
    update_cache: yes
  when: ansible_os_family == 'RedHat'

- name: Install vscode extensions
  ansible.builtin.shell: "code --install-extension {{ item }}"
  with_items:
    - "{{ plugins }}"

- name: Link settings.json and keybindings.json
  ansible.builtin.file:
    src: "{{ role_path }}/files/linux/{{ item }}"
    dest: "/home/{{ ansible_user_id }}/.config/Code/User/{{ item }}"
    state: link
  with_items:
    - keybindings.json
    - settings.json