---
- name: Downloads and installs vscode deb package
  become: yes
  apt:
    state: present
    deb: https://update.code.visualstudio.com/latest/linux-deb-x64/stable

- name: Install vscode extensions
  ansible.builtin.shell: "code --install-extension {{ item }}"
  with_items:
    - "{{ plugins }}"

- name: Link setings.json and keybindings.json
  ansible.builtin.file:
    src: "{{ role_path }}/files/linux/{{ item }}"
    dest: "/home/{{ ansible_user_id }}/.config/Code/User/{{ item }}"
    state: link
  with_items:
    - keybindings.json
    - settings.json