---
- name: Import vscode gpg key
  become: True
  ansible.builtin.rpm_key:
    state: present
    key: "{{ rpm_key_url }}"

- name: Add vscode repository
  become: True
  yum_repository:
    name: vscode
    description: RPM repository of vscode
    baseurl: "{{ yum_repo_url }}"
    gpgcheck: yes
    enabled: yes
    repo_gpgcheck: yes
    gpgkey:
     - "{{ yum_gpg_key_url }}"

- name: Installing vscode
  become: True
  dnf:
    name: code
    state: latest
    update_cache: yes
