---
- name: Installing zsh
  become: yes
  apt:
    name: zsh
    state: latest
  when: ansible_os_family == 'Debian'

- name: Installing zsh
  become: yes
  dnf:
    name: zsh
    state: latest
  when: ansible_os_family == 'RedHat'

- name: Cloning oh-my-zsh
  git:
    repo: "https://github.com/robbyrussell/oh-my-zsh"
    dest: ~/.oh-my-zsh
    force: yes
    update: yes

- name: Link .zshrc
  ansible.builtin.file:
    src: "{{ role_path }}/files/.zshrc"
    dest: "/home/{{ ansible_user_id }}/.zshrc"
    state: link

- name: Get zsh path
  command: which zsh
  register: zsh_path

- name: Set user shell to zsh
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    shell: "{{ zsh_path.stdout }}"

- name: Install thefuck
  become: yes
  ansible.builtin.pip:
    name: thefuck
    state: present

- name: Install zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

- name: Install zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

- name: Cloning powerlevel10k
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: ~/.oh-my-zsh/custom/themes/powerlevel10k
    force: yes
    update: yes

- name: Link .p10k.zsh
  ansible.builtin.file:
    src: "{{ role_path }}/files/.p10k.zsh"
    dest: "/home/{{ ansible_user_id }}/.p10k.zsh"
    state: link
