---
- name: Installing zsh
  become: yes
  apt:
    name: zsh
    state: latest

- name: Cloning oh-my-zsh
  git:
    repo: 'https://github.com/robbyrussell/oh-my-zsh'
    dest: ~/.oh-my-zsh
    force: yes
    update: yes

- name: Link .zshrc
  ansible.builtin.file:
    src: ../files/.zshrc
    dest: "/home/{{ ansible_user_id }}/.zshrc"
    state: link

- name: Get zsh path
  command: which zsh
  register: zsh_path

- name: Set user shell to zsh
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    shell: "{{ zsh_path.stdout }}"

- name: Install thefuck
  pip:
    name: thefuck
    state: present

- name: Install zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

- name: Install zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting