---
- name: Check language support
  ansible.builtin.shell: "check-language-support"
  register: languages

- name: Create language list
  set_fact: 
    lang_list: "{{ languages.stdout.split(' ') }}"

- name: Install language support
  become: yes
  apt:
    state: present
    update_cache: yes
    name: "{{ lang_list }}"
  when: languages.stdout != ""