---
- name: Install kubectl repository key
  become: True
  apt_key:
    url: "{{ apt_repo_key_url }}"
    state: present

- name: Add kubectl repository to sources list
  become: True
  apt_repository:
    repo: "{{ apt_repo_url }}"
    state: present
    filename: kubernetes
