---
- include_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Install kubectl
  become: yes
  package:
    state: present
    name:
      - kubectl
