---
- name: Install required packages
  become: yes
  apt:
    state: present
    update_cache: yes
    name: "{{ packages }}"
  when: ansible_os_family == 'Debian'

- name: Add the Cloud SDK repository key
  become: yes
  apt_key:
    url: "{{ repo_key_url }}"
    state: present
  when: ansible_os_family == 'Debian'

- name: Add Google Cloud SDK repository to sources list
  become: yes
  apt_repository:
    repo: "{{ repo_url }}"
    state: present
    filename: google-cloud-sdk
  when: ansible_os_family == 'Debian'

- name: Install Google Cloud SDK
  become: yes
  apt:
    state: present
    update_cache: yes
    name:
      - google-cloud-sdk
  when: ansible_os_family == 'Debian'

# Fedora
- name: Add Google Cloud SDK repository
  become: yes
  yum_repository:
    name: cloud-sdk
    description: RPM repository of Google Cloud SDK
    baseurl: https://packages.cloud.google.com/yum/repos/cloud-sdk-el8-x86_64
    gpgcheck: yes
    enabled: yes
    repo_gpgcheck: no
    gpgkey:
     - https://packages.cloud.google.com/yum/doc/yum-key.gpg
     - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  when: ansible_os_family == 'RedHat'

- name: Installing Google Cloud SDK
  become: yes
  dnf:
    name: google-cloud-sdk
    state: latest
    update_cache: yes
  when: ansible_os_family == 'RedHat'