---
- name: Downloads and installs Google Chrome browser deb package
  become: yes
  apt:
    state: present
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

- name: Install Google Chrome browser
  become: yes
  apt:
    state: present
    update_cache: yes
    name:
      - google-chrome-stable