---
- name: Install Google Chrome browser repository key
  become: yes
  apt_key:
    url: '{{ item }}'
    state: present
  with_items:
    - https://www.virtualbox.org/download/oracle_vbox_2016.asc
    - https://www.virtualbox.org/download/oracle_vbox.asc

# TODO: check for fingerprint

- name: Add Google Chrome browser repository to sources list
  become: yes
  apt_repository:
    repo: deb https://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: google-chrome

- name: Install Google Chrome browser
  become: yes
  apt:
    state: present
    update_cache: yes
    name:
      - google-chrome-stable