---
- name: Get system information path
  command: uname
  register: osdata

- name: Download terraform-docs version {{ terraform_docs_version }} archive
  ansible.builtin.unarchive:
    src: "https://github.com/terraform-docs/terraform-docs/releases/download/{{ terraform_docs_version }}/terraform-docs-{{ terraform_docs_version }}-{{ osdata.stdout }}-amd64.tar.gz"
    dest: /tmp
    remote_src: yes

- name: Copy terraform-docs to PATH
  ansible.builtin.copy:
    src: "/tmp/terraform-docs"
    dest: ~/.local/bin
    mode: "0755"

- name: Download tfsec in version {{ tfsec_version }}
  get_url:
    url: "https://github.com/aquasecurity/tfsec/releases/download/{{ tfsec_version }}/tfsec-linux-amd64"
    dest: ~/.local/bin/tfsec
    mode: "0550"

- name: Download tflint archive in version {{ tflint_version }}
  ansible.builtin.unarchive:
    src: "https://github.com/terraform-linters/tflint/releases/download/{{ tflint_version }}/tflint_linux_amd64.zip"
    dest: ~/.local/bin
    remote_src: yes

- name: Download terraform-switcher archive in version {{ terraform_switcher_version }}
  ansible.builtin.unarchive:
    src: "https://github.com/warrensbox/terraform-switcher/releases/download/{{ terraform_switcher_version }}/terraform-switcher_{{ terraform_switcher_version }}_{{ osdata.stdout }}_amd64.tar.gz"
    dest: /tmp
    remote_src: yes

- name: Copy terraform-switcher to PATH
  ansible.builtin.copy:
    src: "/tmp/tfswitch"
    dest: ~/.local/bin
    mode: "0755"

- name: Install latest available terraform for major version {{ terraform_version }}
  command: "tfswitch --latest-stable {{ terraform_version }} -b ~/.local/bin/terraform"
