---
- name: Install xz-utils (dependency of apt deb module)
  become: yes
  apt:
    state: present
    update_cache: yes
    name:
      - xz-utils

- name: Downloads and installs minikube deb package
  become: yes
  apt:
    state: present
    deb: https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb