---
# tasks file for powerlevel_fonts
- name: Create .fonts folder
  file:
    state: directory
    path: ~/.fonts
    mode: '0755'

- name: Download fonts
  get_url:
    url: "{{ item.value }}"
    dest: "~/.fonts/{{ item.key }}.ttf"
    mode: "0660"
    force: yes
  loop: "{{ fonts | dict2items }}"

- name: Install Powerline Fonts
  become: yes
  apt:
    state: present
    update_cache: yes
    name:
      - fonts-powerline
  when: ansible_os_family == 'Debian'

- name: Install Powerline Fonts
  become: yes
  dnf:
    state: present
    update_cache: yes
    name:
      - powerline
      - powerline-fonts
      - tmux-powerline
      - vim-powerline
  when: ansible_os_family == 'RedHat'

- name: Update font cache
  shell: fc-cache -f -v